import { 
  Utensils, 
  Fuel, 
  ShoppingBag, 
  FileText, 
  Banknote, 
  Coins, 
  Receipt, 
  Home, 
  Car, 
  Gamepad2, 
  Smartphone, 
  Plane, 
  Hospital, 
  Book, 
  ShieldCheck, 
  Gift, 
  Coffee, 
  Dumbbell, 
  Music, 
  Wifi, 
  Handshake, 
  Wallet,
  Landmark,
  CreditCard,
  TrendingDown,
  TrendingUp,
  UserCheck,
  UserX,
  ShoppingBasket
} from 'lucide-react';

export const ICON_MAP = {
  'Utensils': Utensils,
  'Fuel': Fuel,
  'ShoppingBag': ShoppingBag,
  'FileText': FileText,
  'Banknote': Banknote,
  'Coins': Coins,
  'Receipt': Receipt,
  'Home': Home,
  'Car': Car,
  'Gamepad2': Gamepad2,
  'Smartphone': Smartphone,
  'Plane': Plane,
  'Hospital': Hospital,
  'Book': Book,
  'ShieldCheck': ShieldCheck,
  'Gift': Gift,
  'Coffee': Coffee,
  'Dumbbell': Dumbbell,
  'Music': Music,
  'Wifi': Wifi,
  'Handshake': Handshake,
  'Wallet': Wallet,
  'Landmark': Landmark,
  'CreditCard': CreditCard,
  'TrendingDown': TrendingDown,
  'TrendingUp': TrendingUp,
  'UserCheck': UserCheck,
  'UserX': UserX,
  'ShoppingBasket': ShoppingBasket
};

export const FEATURED_ICONS = [
  { name: 'Utensils', icon: 'Utensils' },
  { name: 'Fuel', icon: 'Fuel' },
  { name: 'ShoppingBag', icon: 'ShoppingBag' },
  { name: 'FileText', icon: 'FileText' },
  { name: 'Banknote', icon: 'Banknote' },
  { name: 'Coins', icon: 'Coins' },
  { name: 'Receipt', icon: 'Receipt' },
  { name: 'Home', icon: 'Home' },
  { name: 'Car', icon: 'Car' },
  { name: 'Gamepad2', icon: 'Gamepad2' },
  { name: 'Smartphone', icon: 'Smartphone' },
  { name: 'Plane', icon: 'Plane' },
  { name: 'Hospital', icon: 'Hospital' },
  { name: 'Book', icon: 'Book' },
  { name: 'ShieldCheck', icon: 'ShieldCheck' },
  { name: 'Gift', icon: 'Gift' },
  { name: 'Coffee', icon: 'Coffee' },
  { name: 'Dumbbell', icon: 'Dumbbell' },
  { name: 'Music', icon: 'Music' },
  { name: 'Handshake', icon: 'Handshake' },
  { name: 'Wallet', icon: 'Wallet' },
  { name: 'Landmark', icon: 'Landmark' },
  { name: 'CreditCard', icon: 'CreditCard' },
  { name: 'ShoppingBasket', icon: 'ShoppingBasket' }
];

// Emoji to Lucide mapping for migration
export const EMOJI_TO_LUCIDE = {
  '🍔': 'Utensils',
  '⛽': 'Fuel',
  '🛍️': 'ShoppingBag',
  '📄': 'FileText',
  '💰': 'Wallet',
  '💵': 'Banknote',
  '💸': 'Banknote',
  '🏦': 'Landmark',
  '🤝': 'Handshake',
  '🏧': 'CreditCard',
  '🏠': 'Home',
  '🚗': 'Car',
  '🎮': 'Gamepad2',
  '📱': 'Smartphone',
  '✈️': 'Plane',
  '🏥': 'Hospital',
  '📚': 'Book'
};
