import { 
  Utensils, 
  Fuel, 
  ShoppingBag, 
  FileText, 
  Banknote, 
  Coins, 
  Receipt, 
  Home, 
  Car, 
  Gamepad2, 
  Smartphone, 
  Plane, 
  Hospital, 
  Book, 
  ShieldCheck, 
  Gift, 
  Coffee, 
  Dumbbell, 
  Music, 
  Wifi, 
  Handshake, 
  Wallet,
  Landmark,
  CreditCard,
  TrendingDown,
  TrendingUp,
  UserCheck,
  UserX,
  ShoppingBasket,
  Bus,
  Train,
  Bike,
  Truck,
  Tv,
  Camera,
  Film,
  Pizza,
  Beer,
  IceCream,
  Heart,
  Stethoscope,
  Activity,
  Hammer,
  Wrench,
  Key,
  Scissors,
  Zap,
  Moon,
  Sun,
  Briefcase,
  Laptop,
  Palette,
  Bell,
  Mail,
  Gamepad,
  Tag,
  Umbrella,
  Wind,
  Cloud,
  Thermometer,
  ZapOff,
  Cpu,
  HardDrive,
  GraduationCap,
  Baby,
  PawPrint,
  Plug,
  Sofa,
  Shirt,
  HeartPulse,
  Monitor,
  Headphones,
  Joystick,
  Mic,
  Music2,
  Brush,
  CameraOff,
  Video,
  Globe,
  Map,
  Compass,
  Anchor,
  Ship,
  Mountain,
  TreePine,
  CloudRain,
  CloudSnow,
  CloudLightning,
  SunDim,
  Sunrise,
  Sunset,
  Flame,
  Droplet,
  GlassWater,
  Apple,
  Croissant,
  ChefHat,
  Trophy,
  Medal,
  Target,
  Dribbble,
  Dices,
  Puzzle,
  Microscope,
  Syringe,
  Pill,
  Bandage,
  Trash2,
  Search,
  Settings,
  BellOff,
  Link,
  Lock,
  Unlock,
  Shield,
  Eye,
  EyeOff,
  User,
  Users,
  Building,
  Store,
  Factory,
  Warehouse,
  Construction,
  PenTool,
  Printer,
  MousePointer,
  Keyboard,
  HardHat,
  Rocket,
  PlaneTakeoff,
  PlaneLanding,
  Ticket,
  MapPin,
  Clock,
  Calendar,
  Hourglass,
  Watch,
  Timer,
  AlarmClock
} from 'lucide-react';

export const ICON_MAP = {
  'Utensils': Utensils,
  'Fuel': Fuel,
  'ShoppingBag': ShoppingBag,
  'FileText': FileText,
  'Banknote': Banknote,
  'Coins': Coins,
  'Receipt': Receipt,
  'Home': Home,
  'Car': Car,
  'Gamepad2': Gamepad2,
  'Smartphone': Smartphone,
  'Plane': Plane,
  'Hospital': Hospital,
  'Book': Book,
  'ShieldCheck': ShieldCheck,
  'Gift': Gift,
  'Coffee': Coffee,
  'Dumbbell': Dumbbell,
  'Music': Music,
  'Wifi': Wifi,
  'Handshake': Handshake,
  'Wallet': Wallet,
  'Landmark': Landmark,
  'CreditCard': CreditCard,
  'TrendingDown': TrendingDown,
  'TrendingUp': TrendingUp,
  'UserCheck': UserCheck,
  'UserX': UserX,
  'ShoppingBasket': ShoppingBasket,
  'Bus': Bus,
  'Train': Train,
  'Bike': Bike,
  'Truck': Truck,
  'Tv': Tv,
  'Camera': Camera,
  'Film': Film,
  'Pizza': Pizza,
  'Beer': Beer,
  'IceCream': IceCream,
  'Heart': Heart,
  'Stethoscope': Stethoscope,
  'Activity': Activity,
  'Hammer': Hammer,
  'Wrench': Wrench,
  'Key': Key,
  'Scissors': Scissors,
  'Zap': Zap,
  'Moon': Moon,
  'Sun': Sun,
  'Briefcase': Briefcase,
  'Laptop': Laptop,
  'Palette': Palette,
  'Bell': Bell,
  'Mail': Mail,
  'Gamepad': Gamepad,
  'Tag': Tag,
  'Umbrella': Umbrella,
  'Wind': Wind,
  'Cloud': Cloud,
  'Thermometer': Thermometer,
  'ZapOff': ZapOff,
  'Cpu': Cpu,
  'HardDrive': HardDrive,
  'GraduationCap': GraduationCap,
  'Baby': Baby,
  'PawPrint': PawPrint,
  'Plug': Plug,
  'Sofa': Sofa,
  'Shirt': Shirt,
  'HeartPulse': HeartPulse,
  'Monitor': Monitor,
  'Headphones': Headphones,
  'Joystick': Joystick,
  'Mic': Mic,
  'Music2': Music2,
  'Brush': Brush,
  'CameraOff': CameraOff,
  'Video': Video,
  'Globe': Globe,
  'Map': Map,
  'Compass': Compass,
  'Anchor': Anchor,
  'Ship': Ship,
  'Mountain': Mountain,
  'TreePine': TreePine,
  'CloudRain': CloudRain,
  'CloudSnow': CloudSnow,
  'CloudLightning': CloudLightning,
  'SunDim': SunDim,
  'Sunrise': Sunrise,
  'Sunset': Sunset,
  'Flame': Flame,
  'Droplet': Droplet,
  'GlassWater': GlassWater,
  'Apple': Apple,
  'Croissant': Croissant,
  'ChefHat': ChefHat,
  'Trophy': Trophy,
  'Medal': Medal,
  'Target': Target,
  'Dribbble': Dribbble,
  'Dices': Dices,
  'Puzzle': Puzzle,
  'Microscope': Microscope,
  'Syringe': Syringe,
  'Pill': Pill,
  'Bandage': Bandage,
  'Trash2': Trash2,
  'Search': Search,
  'Settings': Settings,
  'BellOff': BellOff,
  'Link': Link,
  'Lock': Lock,
  'Unlock': Unlock,
  'Shield': Shield,
  'Eye': Eye,
  'EyeOff': EyeOff,
  'User': User,
  'Users': Users,
  'Building': Building,
  'Store': Store,
  'Factory': Factory,
  'Warehouse': Warehouse,
  'Construction': Construction,
  'PenTool': PenTool,
  'Printer': Printer,
  'MousePointer': MousePointer,
  'Keyboard': Keyboard,
  'HardHat': HardHat,
  'Rocket': Rocket,
  'PlaneTakeoff': PlaneTakeoff,
  'PlaneLanding': PlaneLanding,
  'Ticket': Ticket,
  'MapPin': MapPin,
  'Clock': Clock,
  'Calendar': Calendar,
  'Hourglass': Hourglass,
  'Watch': Watch,
  'Timer': Timer,
  'AlarmClock': AlarmClock
};

export const FEATURED_ICONS = [
  // Food & Drink
  { name: 'Utensils', icon: 'Utensils' },
  { name: 'Coffee', icon: 'Coffee' },
  { name: 'Pizza', icon: 'Pizza' },
  { name: 'Beer', icon: 'Beer' },
  { name: 'IceCream', icon: 'IceCream' },
  { name: 'Apple', icon: 'Apple' },
  { name: 'Croissant', icon: 'Croissant' },
  { name: 'ChefHat', icon: 'ChefHat' },
  { name: 'GlassWater', icon: 'GlassWater' },
  
  // Transport
  { name: 'Car', icon: 'Car' },
  { name: 'Fuel', icon: 'Fuel' },
  { name: 'Bus', icon: 'Bus' },
  { name: 'Train', icon: 'Train' },
  { name: 'Bike', icon: 'Bike' },
  { name: 'Truck', icon: 'Truck' },
  { name: 'Plane', icon: 'Plane' },
  { name: 'PlaneTakeoff', icon: 'PlaneTakeoff' },
  { name: 'Rocket', icon: 'Rocket' },
  { name: 'Ship', icon: 'Ship' },
  
  // Shopping & Services
  { name: 'ShoppingBag', icon: 'ShoppingBag' },
  { name: 'ShoppingBasket', icon: 'ShoppingBasket' },
  { name: 'Store', icon: 'Store' },
  { name: 'Tag', icon: 'Tag' },
  { name: 'Gift', icon: 'Gift' },
  { name: 'Ticket', icon: 'Ticket' },
  { name: 'CreditCard', icon: 'CreditCard' },
  { name: 'Banknote', icon: 'Banknote' },
  { name: 'Wallet', icon: 'Wallet' },
  { name: 'Landmark', icon: 'Landmark' },
  
  // Life & Home
  { name: 'Home', icon: 'Home' },
  { name: 'Building', icon: 'Building' },
  { name: 'Sofa', icon: 'Sofa' },
  { name: 'Shirt', icon: 'Shirt' },
  { name: 'Baby', icon: 'Baby' },
  { name: 'PawPrint', icon: 'PawPrint' },
  { name: 'Plug', icon: 'Plug' },
  { name: 'Trash2', icon: 'Trash2' },
  { name: 'MapPin', icon: 'MapPin' },
  { name: 'Umbrella', icon: 'Umbrella' },
  
  // Work & Tech
  { name: 'Briefcase', icon: 'Briefcase' },
  { name: 'Laptop', icon: 'Laptop' },
  { name: 'Monitor', icon: 'Monitor' },
  { name: 'Smartphone', icon: 'Smartphone' },
  { name: 'Headphones', icon: 'Headphones' },
  { name: 'Keyboard', icon: 'Keyboard' },
  { name: 'Cpu', icon: 'Cpu' },
  { name: 'HardDrive', icon: 'HardDrive' },
  { name: 'Wifi', icon: 'Wifi' },
  { name: 'MousePointer', icon: 'MousePointer' },
  { name: 'Printer', icon: 'Printer' },
  
  // Health & Sports
  { name: 'Hospital', icon: 'Hospital' },
  { name: 'Heart', icon: 'Heart' },
  { name: 'HeartPulse', icon: 'HeartPulse' },
  { name: 'Activity', icon: 'Activity' },
  { name: 'Stethoscope', icon: 'Stethoscope' },
  { name: 'Pill', icon: 'Pill' },
  { name: 'Syringe', icon: 'Syringe' },
  { name: 'Bandage', icon: 'Bandage' },
  { name: 'Dumbbell', icon: 'Dumbbell' },
  { name: 'Trophy', icon: 'Trophy' },
  { name: 'Medal', icon: 'Medal' },
  { name: 'Target', icon: 'Target' },
  { name: 'Dribbble', icon: 'Dribbble' },
  
  // Entertainment & Hobby
  { name: 'Tv', icon: 'Tv' },
  { name: 'Gamepad', icon: 'Gamepad' },
  { name: 'Joystick', icon: 'Joystick' },
  { name: 'Music', icon: 'Music' },
  { name: 'Music2', icon: 'Music2' },
  { name: 'Camera', icon: 'Camera' },
  { name: 'Video', icon: 'Video' },
  { name: 'Film', icon: 'Film' },
  { name: 'Palette', icon: 'Palette' },
  { name: 'Brush', icon: 'Brush' },
  { name: 'Dices', icon: 'Dices' },
  { name: 'Puzzle', icon: 'Puzzle' },
  { name: 'Book', icon: 'Book' },
  { name: 'GraduationCap', icon: 'GraduationCap' },
  
  // Nature & Weather
  { name: 'Mountain', icon: 'Mountain' },
  { name: 'TreePine', icon: 'TreePine' },
  { name: 'Globe', icon: 'Globe' },
  { name: 'Compass', icon: 'Compass' },
  { name: 'Anchor', icon: 'Anchor' },
  { name: 'Sun', icon: 'Sun' },
  { name: 'Moon', icon: 'Moon' },
  { name: 'Cloud', icon: 'Cloud' },
  { name: 'CloudRain', icon: 'CloudRain' },
  { name: 'CloudSnow', icon: 'CloudSnow' },
  { name: 'CloudLightning', icon: 'CloudLightning' },
  { name: 'Wind', icon: 'Wind' },
  { name: 'Thermometer', icon: 'Thermometer' },
  { name: 'Flame', icon: 'Flame' },
  { name: 'Droplet', icon: 'Droplet' },
  { name: 'Zap', icon: 'Zap' },
  
  // Tools & Security
  { name: 'Hammer', icon: 'Hammer' },
  { name: 'Wrench', icon: 'Wrench' },
  { name: 'Key', icon: 'Key' },
  { name: 'Scissors', icon: 'Scissors' },
  { name: 'PenTool', icon: 'PenTool' },
  { name: 'HardHat', icon: 'HardHat' },
  { name: 'Construction', icon: 'Construction' },
  { name: 'ShieldCheck', icon: 'ShieldCheck' },
  { name: 'Lock', icon: 'Lock' },
  { name: 'Unlock', icon: 'Unlock' },
  
  // Misc
  { name: 'Bell', icon: 'Bell' },
  { name: 'Mail', icon: 'Mail' },
  { name: 'User', icon: 'User' },
  { name: 'Users', icon: 'Users' },
  { name: 'Handshake', icon: 'Handshake' },
  { name: 'Clock', icon: 'Clock' },
  { name: 'Calendar', icon: 'Calendar' },
  { name: 'Hourglass', icon: 'Hourglass' },
  { name: 'Watch', icon: 'Watch' }
];

// Emoji to Lucide mapping for migration
export const EMOJI_TO_LUCIDE = {
  '🍔': 'Utensils',
  '⛽': 'Fuel',
  '🛍️': 'ShoppingBag',
  '📄': 'FileText',
  '💰': 'Wallet',
  '💵': 'Banknote',
  '💸': 'Banknote',
  '🏦': 'Landmark',
  '🤝': 'Handshake',
  '🏧': 'CreditCard',
  '🏠': 'Home',
  '🚗': 'Car',
  '🎮': 'Gamepad2',
  '📱': 'Smartphone',
  '✈️': 'Plane',
  '🏥': 'Hospital',
  '📚': 'Book'
};
