import { 
  Utensils, Fuel, ShoppingBag, FileText, Banknote, Coins, Receipt, 
  Home, Car, Gamepad2, Smartphone, Plane, Hospital, Book, 
  ShieldCheck, Gift, Coffee, Dumbbell, Music, Wifi, Handshake, 
  Wallet, Landmark, CreditCard, TrendingDown, TrendingUp, UserCheck, 
  UserX, ShoppingBasket, Sprout, Tractor, Leaf, Trees, Wrench, 
  Hammer, HardHat, Construction, Building, Fence, Droplets, Shovel
} from 'lucide-react';

export const ICON_MAP: Record<string, any> = {
  'Utensils': Utensils,
  'Fuel': Fuel,
  'ShoppingBag': ShoppingBag,
  'FileText': FileText,
  'Banknote': Banknote,
  'Coins': Coins,
  'Receipt': Receipt,
  'Home': Home,
  'Car': Car,
  'Gamepad2': Gamepad2,
  'Smartphone': Smartphone,
  'Plane': Plane,
  'Hospital': Hospital,
  'Book': Book,
  'ShieldCheck': ShieldCheck,
  'Gift': Gift,
  'Coffee': Coffee,
  'Dumbbell': Dumbbell,
  'Music': Music,
  'Wifi': Wifi,
  'Handshake': Handshake,
  'Wallet': Wallet,
  'Landmark': Landmark,
  'CreditCard': CreditCard,
  'TrendingDown': TrendingDown,
  'TrendingUp': TrendingUp,
  'UserCheck': UserCheck,
  'UserX': UserX,
  'ShoppingBasket': ShoppingBasket,
  'Sprout': Sprout,
  'Tractor': Tractor,
  'Leaf': Leaf,
  'Trees': Trees,
  'Wrench': Wrench,
  'Hammer': Hammer,
  'HardHat': HardHat,
  'Construction': Construction,
  'Building': Building,
  'Fence': Fence,
  'Droplets': Droplets,
  'Shovel': Shovel
};
